[package]
name = "aurae-client-macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
heck = "0.4.0"
proc-macro2 = "1.0.44"
quote = "1.0.21"
syn = { version = "1.0.101", features = ['full'] }