name: Documentation
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: build-docs-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          sudo apt-get install -y libdbus-1-dev pkg-config libseccomp-dev
          wget https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.1/protoc-gen-doc_1.5.1_linux_amd64.tar.gz
          tar -xzf protoc-gen-doc_1.5.1_linux_amd64.tar.gz
          chmod +x protoc-gen-doc
          cp protoc-gen-doc /usr/local/bin/protoc-gen-doc
      - name: Check documenation
        run: |
          wget --output-document=vale.tar.gz https://github.com/errata-ai/vale/releases/download/v2.21.3/vale_2.21.3_Linux_64-bit.tar.gz
          mkdir bin && tar -xvzf vale.tar.gz -C bin
          export PATH="$PWD/bin:$PATH"

          make check-docs
      - name: Build documentation
        run: |
          make docs
