name: compile and test

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install protobuf-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Checkout the aurae api
        run: git clone https://github.com/aurae-runtime/api ../api
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
