name: Deploy (aurae.io)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          sudo apt-get install -y libdbus-1-dev pkg-config libseccomp-dev
          wget https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.1/protoc-gen-doc_1.5.1_linux_amd64.tar.gz
          tar -xzf protoc-gen-doc_1.5.1_linux_amd64.tar.gz
          chmod +x protoc-gen-doc
          cp protoc-gen-doc /usr/local/bin/protoc-gen-doc
          pip install mkdocs-material
      - name: Build website
        run: make docs
      - name: Deploy website
        run: mkdocs gh-deploy --force